import flet as ft

PAGE_COLOR = ft.Colors.GREY_900
WINDOW_COLOR = ft.Colors.BLACK
BOX_COLOR = ft.Colors.GREY_800
TEXT_COLOR = ft.Colors.WHITE
LINE_COLOR = ft.Colors.GREY_700
LABEL_COLOR = ft.Colors.GREY_500
PADDING = 15
RADIUS = 10
HOUR_HEIGHT = 55
LABEL_WIDTH = 40
EVENT_HOURS = [9, 10, 14, 15, 16]
GRID_ITEM_COUNT = 48

ADD_BUTTON_MINI = False
ADD_BUTTON_RIGHT = 30
ADD_BUTTON_BOTTOM = 30
